development:
  forest_env_secret: 6eaa1d492828b78cca93738a1e8e665e6e4315d39b3fe5071be6a377cc433707
  forest_auth_secret: _PQfuyDbnUjfRzr5qe_O5Q
  forest_application_url: http://localhost:3001
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
